#!/usr/bin/env python3
"""Convert protocols_extracted.txt (slide-marker dump) to a structured protocols.md."""
import re
import sys
from pathlib import Path

SRC = Path(__file__).parent / "protocols_extracted.txt"
OUT = Path(__file__).parent / "protocols.md"
SHIM = Path(__file__).parent / "protocols_kb.js"

SLIDE_RE = re.compile(r"^=== שקף (\d+) ===$")
URL_GLUE_RE = re.compile(r"([\u0590-\u05FFA-Za-z]) *(https?://)")
TRIM_WS_RE = re.compile(r"[ \t]+")


def clean_line(line: str) -> str:
    line = line.replace("\u200f", "").replace("\u200e", "")
    line = TRIM_WS_RE.sub(" ", line).strip()
    # Split phrases glued directly to a URL (common artifact of PPTX extraction)
    line = URL_GLUE_RE.sub(r"\1 \2", line)
    return line


def is_noise(line: str) -> bool:
    if not line:
        return True
    if re.fullmatch(r"[-=–—•·\*\s]+", line):
        return True
    return False


def split_bulletable(body_lines):
    """A heuristic: if a slide body is mostly short independent lines, render as list."""
    if len(body_lines) <= 1:
        return False
    short = sum(1 for l in body_lines if len(l) <= 90)
    return short / len(body_lines) >= 0.6


def render_slide(num: int, title: str, body_lines, out):
    out.append("")
    heading = title.strip() if title else f"שקף {num}"
    # Remove trailing colons/dashes from the title itself.
    heading = heading.rstrip(" :-–—")
    out.append(f"## שקף {num} — {heading}")
    out.append("")
    if not body_lines:
        out.append("_(ללא תוכן נוסף)_")
        return
    if split_bulletable(body_lines):
        for line in body_lines:
            # Lines that already look like sub-headers get promoted.
            if re.match(r"^[\u0590-\u05FFA-Za-z][^\n]{0,40}:$", line):
                out.append("")
                out.append(f"**{line.rstrip(':')}**")
                out.append("")
                continue
            out.append(f"- {line}")
    else:
        for line in body_lines:
            out.append(line)
            out.append("")


def main():
    text = SRC.read_text(encoding="utf-8").splitlines()
    slides = []  # list of (num, title, body)
    current = None
    for raw in text:
        line = clean_line(raw)
        m = SLIDE_RE.match(line)
        if m:
            if current:
                slides.append(current)
            current = {"num": int(m.group(1)), "lines": []}
            continue
        if current is None:
            continue
        if is_noise(line):
            continue
        current["lines"].append(line)
    if current:
        slides.append(current)

    # Deduplicate consecutive identical lines (common extraction artifact).
    for s in slides:
        dedup = []
        prev = None
        for l in s["lines"]:
            if l != prev:
                dedup.append(l)
                prev = l
        s["lines"] = dedup

    out = [
        "# תיק חפיפה — מנהלי אירועים מבצעיים",
        "",
        "> מסמך זה הוא מקור האמת היחיד של Super Magnus. כל הפרוטוקולים, הנהלים והמידע המבצעי מתועדים כאן.",
        "> המסמך נוצר מהמצגת `protocolsbook.pptx` (265 שקפים).",
        "",
        "---",
        "",
    ]

    for s in slides:
        title = s["lines"][0] if s["lines"] else ""
        body = s["lines"][1:] if s["lines"] else []
        # Guard: if title is absurdly long, treat the whole slide as body.
        if len(title) > 120:
            body = s["lines"]
            title = f"שקף {s['num']}"
        render_slide(s["num"], title, body, out)

    md_text = "\n".join(out).rstrip() + "\n"
    OUT.write_text(md_text, encoding="utf-8")

    # Transport shim: mirrors protocols.md byte-for-byte as a JS string literal so
    # the HTML can load it via <script src> when opened over file:// (no fetch).
    # Source of truth remains protocols.md — the shim is a generated artifact.
    escaped = md_text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    shim = (
        "// Auto-generated by build_protocols_md.py — DO NOT EDIT BY HAND.\n"
        "// Source of truth: protocols.md\n"
        f"window.MAGNUS_PROTOCOLS_MD = `{escaped}`;\n"
    )
    SHIM.write_text(shim, encoding="utf-8")
    print(f"Wrote {OUT} and {SHIM} — {len(slides)} slides")


if __name__ == "__main__":
    main()
